version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ${DOCKER_ENV:-Dockerfile.debug}
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    depends_on:
      - db
      - cache
    volumes:
      - .:/app:rw,delegated
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      - REDIS_URL=redis://cache:${REDIS_PORT}
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  cache:
    image: redis:latest
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

volumes:
  pgdata: